'use client';

import { useState, type ReactNode } from 'react';
import Link from 'next/link';
import './admin.css';
import {
  Activity, BarChart3, Bell, BookOpen, Check, ChevronDown, ChevronLeft, ChevronRight,
  CircleAlert, ClipboardList, Database, FileWarning, Globe2, LayoutDashboard, Link2,
  Mail, Menu, MessageSquareText, MoreHorizontal, Network, Phone, Plus, RefreshCcw,
  Save, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, TrendingUp,
  UserPlus, Users, Workflow, X, Zap,
} from 'lucide-react';

const navigation = [
  ['Overview', LayoutDashboard], ['Fraud reports', FileWarning], ['Phone numbers', Phone],
  ['Fraud intelligence', Network], ['Fraud patterns', Workflow], ['Fraud checks', ShieldCheck],
  ['Detection rules', SlidersHorizontal], ['Users', Users], ['Analytics', BarChart3],
  ['Education content', BookOpen], ['Audit logs', ClipboardList], ['Settings', Settings],
] as const;
type NavLabel = typeof navigation[number][0];
type Tone = 'violet' | 'orange' | 'gold' | 'green';
type Row = { name: string; id: string; cells: string[]; status: string; tone: Tone };
type Tab = { eyebrow: string; description: string; action: string; stats: [string,string,string,Tone][]; title: string; columns: string[]; rows: Row[]; sideTitle: string; side: [string,string,string,number,Tone][] };

const tabs: Record<Exclude<NavLabel, 'Overview' | 'Settings'>, Tab> = {
  'Fraud reports': {
    eyebrow:'Community operations', description:'Review, verify and resolve fraud reports submitted by the Guard community.', action:'New report', title:'Reports requiring attention',
    stats:[['Open reports','148','+18 today','violet'],['Awaiting review','48','12 due today','orange'],['Verified signals','1,204','86% confidence','green'],['Median review time','2h 14m','18 min faster','gold']], columns:['Category','Entity','Amount','Submitted'],
    rows:[r('Delivery payment impersonation','GRD-RPT-1842',['Phishing','swift-delivery.co','GH₵ 420','8 min ago'],'Under review','orange'),r('Mobile money reversal request','GRD-RPT-1839',['Mobile money','+233 24 891 2041','GH₵ 1,250','26 min ago'],'Submitted','violet'),r('Investment group guarantee','GRD-RPT-1836',['Investment','@wealthcirclegh','GH₵ 5,000','43 min ago'],'Verified','green'),r('Bank support impersonation','GRD-RPT-1828',['Impersonation','+233 55 203 7810','—','1 hr ago'],'Needs evidence','gold')],
    sideTitle:'Leading categories', side:[['Mobile money','38%','244 reports',88,'orange'],['Impersonation','27%','173 reports',64,'violet'],['Phishing links','21%','135 reports',49,'gold'],['Investment fraud','14%','90 reports',33,'green']],
  },
  'Phone numbers': {
    eyebrow:'Entity reputation', description:'Search and monitor phone numbers connected to reported or detected fraud activity.', action:'Add number', title:'Recently active numbers',
    stats:[['Numbers monitored','9,842','+126 this week','violet'],['High-risk numbers','782','7.9% of total','orange'],['Newly reported','64','Last 24 hours','gold'],['Cleared appeals','18','This month','green']], columns:['Network','Reports','Risk score','Last activity'],
    rows:[r('+233 24 891 2041','Ghana · Mobile',['MTN Ghana','34','94 / 100','6 min ago'],'High risk','orange'),r('+233 55 203 7810','Ghana · Mobile',['MTN Ghana','17','78 / 100','31 min ago'],'Caution','gold'),r('+233 20 117 9022','Ghana · Mobile',['Telecel','9','66 / 100','2 hr ago'],'Monitoring','violet'),r('+233 27 450 1138','Ghana · Mobile',['AT Ghana','2','22 / 100','Yesterday'],'Low risk','green')],
    sideTitle:'Reports by network', side:[['MTN Ghana','62%','486 flagged',86,'orange'],['Telecel','21%','165 flagged',48,'violet'],['AT Ghana','12%','94 flagged',31,'gold'],['Other / VoIP','5%','37 flagged',17,'green']],
  },
  'Fraud intelligence': {
    eyebrow:'Threat intelligence', description:'Connect entities, signals and incidents to understand active fraud campaigns.', action:'Create intelligence', title:'Active intelligence briefs',
    stats:[['Active campaigns','14','3 critical','orange'],['Connected entities','3,286','+8.4% this month','violet'],['Signals ingested','48.2k','Last 24 hours','gold'],['Confidence average','87%','+4.2 points','green']], columns:['Channel','Entities','Confidence','First seen'],
    rows:[r('Courier fee impersonation cluster','INT-092 · 6 linked incidents',['SMS + Web','42','96%','Today, 07:14'],'Escalated','orange'),r('False job placement network','INT-089 · 11 linked incidents',['WhatsApp','28','91%','Yesterday'],'Tracking','violet'),r('Crypto mentorship campaign','INT-087 · 4 linked incidents',['Telegram','16','84%','25 Sep'],'Assessing','gold'),r('Account recovery impersonators','INT-081 · 9 linked incidents',['Voice + SMS','23','79%','21 Sep'],'Contained','green')],
    sideTitle:'Signal velocity', side:[['Impersonation','+28%','Rising rapidly',92,'orange'],['Urgency language','+16%','Above baseline',71,'gold'],['Payment redirects','+9%','Moderate rise',54,'violet'],['Remote access','−4%','Declining',31,'green']],
  },
  'Fraud patterns': {
    eyebrow:'Pattern library', description:'Maintain the patterns that help analysts and rules classify active threats.', action:'New pattern', title:'Detection-ready patterns',
    stats:[['Active patterns','38','Across 9 categories','violet'],['High severity','12','4 updated recently','orange'],['Checks matched','6,481','Last 30 days','gold'],['Detection coverage','92%','+3% this quarter','green']], columns:['Category','Severity','Matches','Updated'],
    rows:[r('Mobile money reversal scam','PAT-014 · 7 signals',['Mobile money','Critical','1,842','Today'],'Active','green'),r('Trusted brand impersonation','PAT-009 · 5 signals',['Impersonation','High','1,306','Yesterday'],'Active','green'),r('Guaranteed return investment','PAT-022 · 6 signals',['Investment','High','904','24 Sep'],'Tuning','gold'),r('Fake delivery clearance fee','PAT-031 · 4 signals',['Phishing','Medium','438','19 Sep'],'Draft','violet')],
    sideTitle:'Patterns by category', side:[['Mobile money','9','24% of library',82,'orange'],['Impersonation','8','21% of library',71,'violet'],['Phishing','7','18% of library',62,'gold'],['Investment','5','13% of library',44,'green']],
  },
  'Fraud checks': {
    eyebrow:'Detection activity', description:'Inspect every message, number and link analysed by the Guard detection engine.', action:'Run a check', title:'Latest fraud checks',
    stats:[['Checks today','18,426','+12.4% vs yesterday','violet'],['High risk','2,184','11.9% of checks','orange'],['Caution','4,091','22.2% of checks','gold'],['Low risk','12,151','65.9% of checks','green']], columns:['Type','Risk score','Pattern','Checked'],
    rows:[r('“Send the OTP now to reverse…”','CHK-88429 · Message',['Message','96 / 100','MoMo reversal','Just now'],'High risk','orange'),r('swift-delivery.co/clearance','CHK-88428 · Link',['Link','89 / 100','Delivery fee','1 min ago'],'High risk','orange'),r('+233 55 203 7810','CHK-88424 · Phone',['Phone','78 / 100','Impersonation','4 min ago'],'Caution','gold'),r('gcb.com.gh','CHK-88418 · Link',['Link','08 / 100','No match','7 min ago'],'Low risk','green')],
    sideTitle:'Checks by input type', side:[['Messages','44%','8,107 checks',88,'violet'],['Phone numbers','28%','5,159 checks',61,'orange'],['Links','21%','3,869 checks',47,'gold'],['Images','7%','1,291 checks',21,'green']],
  },
  'Detection rules': {
    eyebrow:'Detection engine', description:'Create and tune the rules that score signals and trigger analyst review.', action:'Create rule', title:'Detection rules',
    stats:[['Active rules','42','5 rule groups','violet'],['Triggered today','3,862','+9.1% vs yesterday','orange'],['Precision rate','91.8%','+1.6 points','green'],['Rules in draft','6','2 awaiting approval','gold']], columns:['Signal group','Weight','Triggered','Modified'],
    rows:[r('Credential or OTP request','RULE-OTP-01',['Credentials','+35','1,284','Today'],'Active','green'),r('Remote access application request','RULE-RMT-03',['Device access','+40','416','Yesterday'],'Active','green'),r('Guaranteed return language','RULE-INV-06',['Investment','+25','892','25 Sep'],'Testing','gold'),r('Newly registered payment domain','RULE-WEB-12',['Web risk','+20','207','18 Sep'],'Draft','violet')],
    sideTitle:'Best performing rules', side:[['PIN request','98.2%','Precision',98,'orange'],['Remote access','96.4%','Precision',96,'violet'],['Suspicious domain','93.1%','Precision',93,'gold'],['Impersonation','89.7%','Precision',90,'green']],
  },
  'Users': {
    eyebrow:'Access management', description:'Manage members, roles and account health across the Guard workspace.', action:'Invite user', title:'Members and access',
    stats:[['Total users','24,892','+642 this month','violet'],['Active this week','16,410','65.9% active','green'],['Admin members','18','4 role groups','gold'],['Restricted accounts','27','8 under review','orange']], columns:['Role','Checks','Reports','Last active'],
    rows:[r('Ama Osei','ama.osei@guard.africa',['Fraud analyst','1,204','184','Online now'],'Active','green'),r('Kojo Mensah','kojo.mensah@guard.africa',['Super admin','986','112','4 min ago'],'Active','green'),r('Esi Boateng','esi.boateng@guard.africa',['Support admin','644','96','1 hr ago'],'Active','green'),r('Nana K. Owusu','nana.owusu@example.com',['User','32','4','22 Sep'],'Restricted','orange')],
    sideTitle:'Users by role', side:[['Community users','99.7%','24,816 users',99,'violet'],['Fraud analysts','32','Internal access',58,'orange'],['Support admins','26','Limited admin',43,'gold'],['Super admins','18','Full access',31,'green']],
  },
  'Analytics': {
    eyebrow:'Performance analytics', description:'Explore how people use Guard and how effectively threats are being detected.', action:'Export report', title:'Detection by channel',
    stats:[['Detection rate','88.4%','+3.2 points','violet'],['Checks per user','7.4','+0.8 this month','orange'],['Reports converted','34.1%','+4.6 points','gold'],['Loss prevented','GH₵ 2.8m','Estimated','green']], columns:['Checks','High risk','Report rate','Change'],
    rows:[r('WhatsApp messages','Consumer channel',['7,842','1,286','18.4%','+24.2%'],'Growing','orange'),r('SMS messages','Consumer channel',['4,918','672','12.8%','+8.7%'],'Stable','green'),r('Web links','All channels',['3,869','524','9.6%','+15.1%'],'Growing','violet'),r('Phone numbers','Lookup tool',['1,797','314','22.1%','−2.4%'],'Stable','green')],
    sideTitle:'Monthly goals', side:[['Checks completed','82%','184k of 225k',82,'violet'],['Review SLA','94%','Target 90%',94,'green'],['User education','68%','Target 75%',68,'gold'],['Report resolution','88%','Target 92%',88,'orange']],
  },
  'Education content': {
    eyebrow:'Knowledge centre', description:'Publish practical fraud education and keep community guidance up to date.', action:'Create article', title:'Articles and guides',
    stats:[['Published articles','64','9 collections','violet'],['Monthly readers','38.2k','+18.7%','orange'],['Completion rate','72%','+6 points','green'],['Drafts awaiting review','7','3 assigned','gold']], columns:['Collection','Views','Updated','Owner'],
    rows:[r('How mobile money reversal scams work','6 min read · Beginner',['Mobile money','12,482','Today','Akua Danso'],'Published','green'),r('Spotting a fake delivery payment link','4 min read · Beginner',['Phishing','8,204','Yesterday','Kofi Amankwa'],'Published','green'),r('Before you join an investment group','8 min read · Intermediate',['Investment','5,661','24 Sep','Ama Osei'],'In review','gold'),r('Protecting your one-time password','3 min read · Beginner',['Account safety','—','21 Sep','Esi Boateng'],'Draft','violet')],
    sideTitle:'Popular collections', side:[['Mobile money safety','14.8k','Monthly readers',91,'orange'],['Phishing awareness','10.2k','Monthly readers',73,'violet'],['Account protection','8.1k','Monthly readers',58,'gold'],['Investment safety','5.1k','Monthly readers',39,'green']],
  },
  'Audit logs': {
    eyebrow:'Governance trail', description:'Review security-sensitive actions and changes made across the workspace.', action:'Export logs', title:'Recent audit activity',
    stats:[['Events today','1,284','Across 42 actors','violet'],['Admin changes','86','6 privileged','gold'],['Security events','12','2 need review','orange'],['Retention window','365 days','Policy compliant','green']], columns:['Action','Target','IP address','Time'],
    rows:[r('Ama Osei','Fraud analyst · AO',['Report status changed','GRD-RPT-1842','197.251.18.42','2 min ago'],'Successful','green'),r('Kojo Mensah','Super admin · KM',['Rule updated','RULE-OTP-01','102.176.94.8','18 min ago'],'Successful','green'),r('System automation','Guard intelligence engine',['User restricted','USR-29184','Internal','34 min ago'],'Automated','violet'),r('Unknown session','Authentication gateway',['Admin login attempted','admin@guard.africa','41.66.204.17','1 hr ago'],'Blocked','orange')],
    sideTitle:'Events by action', side:[['Data viewed','54%','694 events',88,'violet'],['Records changed','28%','360 events',61,'orange'],['Exports created','11%','141 events',35,'gold'],['Access events','7%','89 events',23,'green']],
  },
};

function r(name:string,id:string,cells:string[],status:string,tone:Tone):Row { return {name,id,cells,status,tone}; }
const incidents = [r('High-volume OTP requests from new device cluster','GRD-2418',['Mobile money','8 min ago','Ama Osei'],'Monitoring','orange'),r('Impersonation campaign using delivery links','GRD-2417',['Phishing','14 min ago','Kojo Mensah'],'Investigating','orange'),r('Repeated transfers to a reported account','GRD-2413',['Bank transfer','31 min ago','Esi Boateng'],'Under review','gold'),r('Suspicious merchant domain registrations','GRD-2409',['Online merchant','1 hr ago','Nii Addo'],'Resolved','green')];
const overviewStats: Tab['stats'] = [['Total fraud checks','18,426','+12.4% vs previous period','violet'],['High-risk checks','2,184','+8.2% require attention','orange'],['Reports received','642','+16.8% vs previous period','gold'],['Pending reviews','48','12 due today','violet']];
const contributors = [['Impersonation',74],['Urgency language',61],['OTP request',48],['Payment redirect',37]] as const;

function tone(t:Tone){return `tone-${t}`;}
function StatGrid({stats}:{stats:Tab['stats']}) { const icons=[ShieldCheck,CircleAlert,TrendingUp,ClipboardList]; return <section className="ga-stat-grid">{stats.map(([label,value,note,t],i)=>{const Icon=icons[i];return <article className="ga-stat" key={label}><div className={`ga-stat-icon ${tone(t)}`}><Icon size={19}/></div><div className="ga-stat-copy"><span>{label}</span><strong>{value}</strong><small className={t==='orange'?'alert':t==='gold'?'warning':''}>{note}</small></div><Sparkles className="ga-stat-spark" size={16}/></article>})}</section> }
function Status({text,t}:{text:string;t:Tone}) { return <span className={`ga-status-pill ${tone(t)}`}><i/>{text}</span>; }

function DataTable({title,columns,rows,query}:{title:string;columns:string[];rows:Row[];query:string}) { const filtered=rows.filter(row=>[row.name,row.id,row.status,...row.cells].join(' ').toLowerCase().includes(query.toLowerCase())); return <section className="ga-panel ga-directory"><div className="ga-panel-head ga-directory-head"><div><span className="ga-panel-kicker">Live workspace</span><h2>{title}</h2><p>{filtered.length} of {rows.length} records shown</p></div><div className="ga-segments"><button className="active">All</button><button>Attention</button><button>Resolved</button></div></div><div className="ga-table-wrap ga-flex-table"><table><thead><tr><th>Name / ID</th>{columns.map(x=><th key={x}>{x}</th>)}<th>Status</th><th/></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><strong>{row.name}</strong><small>{row.id}</small></td>{row.cells.map((cell,i)=><td key={i}>{cell}</td>)}<td><Status text={row.status} t={row.tone}/></td><td><button aria-label={`Open ${row.id}`}><ChevronRight size={16}/></button></td></tr>)}</tbody></table>{filtered.length===0&&<div className="ga-empty"><Search size={24}/><strong>No matching records</strong><span>Clear the search or try another term.</span></div>}</div></section> }
function Breakdown({title,items,onAction}:{title:string;items:Tab['side'];onAction:()=>void}) { return <aside className="ga-panel ga-breakdown"><div className="ga-panel-head"><div><span className="ga-panel-kicker">Live breakdown</span><h2>{title}</h2></div><button><MoreHorizontal size={17}/></button></div><div className="ga-breakdown-list">{items.map(([label,value,detail,progress,t])=><div className="ga-breakdown-item" key={label}><div><span>{label}</span><strong>{value}</strong></div><div className="ga-progress"><i className={tone(t)} style={{width:`${progress}%`}}/></div><small>{detail}</small></div>)}</div><button className="ga-side-action" onClick={onAction}>View detailed breakdown <ChevronRight size={14}/></button></aside> }
function matching(tab:Tab,query:string){return tab.rows.filter(row=>[row.name,row.id,row.status,...row.cells].join(' ').toLowerCase().includes(query.toLowerCase()))}

function ReportsView({tab,query,onAction}:{tab:Tab;query:string;onAction:()=>void}) { const rows=matching(tab,query); const groups=[['New reports',rows.slice(0,2),'violet'],['In review',rows.slice(1,3),'orange'],['Resolved',rows.slice(2),'green']] as const; return <><StatGrid stats={tab.stats}/><div className="ga-queue-toolbar"><div><strong>Investigation board</strong><span>Move reports through the verification workflow.</span></div><button onClick={onAction}><Plus size={15}/>Add report</button></div><section className="ga-kanban">{groups.map(([label,items,t])=><div className="ga-kanban-col" key={label}><header><span><i className={`tone-${t}`}/>{label}</span><b>{items.length}</b></header><div>{items.map((row,index)=><article className="ga-case-card" key={`${label}-${row.id}`}><div><Status text={row.status} t={row.tone}/><button><MoreHorizontal size={16}/></button></div><h3>{row.name}</h3><p>{row.id} · {row.cells[0]}</p><dl><div><dt>Entity</dt><dd>{row.cells[1]}</dd></div><div><dt>Exposure</dt><dd>{row.cells[2]}</dd></div></dl><footer><span className="ga-avatar ga-avatar-small">{index%2?'KM':'AO'}</span><span>{row.cells[3]}</span><button>Review <ChevronRight size={13}/></button></footer></article>)}</div></div>)}</section></> }

function PhoneView({tab,query,onAction}:{tab:Tab;query:string;onAction:()=>void}) { const [number,setNumber]=useState(query||'+233 24 891 2041'); return <><section className="ga-phone-hero"><div><span className="ga-panel-kicker">Instant reputation search</span><h2>Investigate a phone number</h2><p>See linked reports, network details and recent risk activity before taking action.</p><div className="ga-phone-search"><Phone size={18}/><input value={number} onChange={e=>setNumber(e.target.value)} aria-label="Phone number"/><button onClick={onAction}>Run lookup</button></div><small>Supports Ghanaian and international formats</small></div><div className="ga-score-orbit"><div><strong>94</strong><span>High risk</span></div><i/><i/><i/></div></section><div className="ga-phone-facts"><article><span>Network</span><strong>MTN Ghana</strong><small>Mobile · Ghana</small></article><article><span>Community reports</span><strong>34</strong><small>From 29 independent reporters</small></article><article><span>First reported</span><strong>14 Aug 2026</strong><small>Last active 6 minutes ago</small></article><article><span>Linked patterns</span><strong>3 matches</strong><small>MoMo reversal · impersonation</small></article></div><div className="ga-workspace-grid"><DataTable title="Watchlisted numbers" columns={tab.columns} rows={tab.rows} query={query}/><Breakdown title={tab.sideTitle} items={tab.side} onAction={onAction}/></div></> }

function IntelligenceView({tab,onAction}:{tab:Tab;onAction:()=>void}) { return <><div className="ga-intel-grid"><section className="ga-threat-map"><div className="ga-threat-map-head"><div><span>Live entity graph</span><h2>Courier impersonation cluster</h2></div><button onClick={onAction}>Open investigation <ChevronRight size={14}/></button></div><div className="ga-network-map"><svg viewBox="0 0 700 330" preserveAspectRatio="none"><path d="M350 160L150 75M350 160L130 245M350 160L560 65M350 160L585 245M150 75L70 160M560 65L665 145M130 245L270 290M585 245L450 300"/></svg><button className="node main"><Network size={22}/><b>INT-092</b><small>Campaign</small></button><button className="node n1"><Globe2 size={16}/><b>swift-delivery.co</b><small>Domain · 96 risk</small></button><button className="node n2"><Phone size={16}/><b>+233 24 891…</b><small>Phone · 94 risk</small></button><button className="node n3"><MessageSquareText size={16}/><b>18 messages</b><small>Shared language</small></button><button className="node n4"><FileWarning size={16}/><b>6 reports</b><small>Community evidence</small></button></div><div className="ga-map-legend"><span><i className="critical"/>Critical entity</span><span><i/>Linked signal</span><span><i className="report"/>Community report</span></div></section><aside className="ga-panel ga-live-feed"><div className="ga-panel-head"><div><span className="ga-panel-kicker">Signal stream</span><h2>Live intelligence</h2></div><span className="ga-live-dot">Live</span></div>{tab.rows.map((row,index)=><article key={row.id}><i className={`tone-${row.tone}`}/><div><strong>{row.name}</strong><span>{row.cells[0]} · {row.cells[2]} confidence</span><small>{index*11+2} minutes ago</small></div></article>)}</aside></div><section className="ga-signal-strip">{tab.side.map(([label,value,detail,,t])=><article key={label}><span className={`tone-${t}`}>{value}</span><div><strong>{label}</strong><small>{detail}</small></div><TrendingUp size={16}/></article>)}</section></> }

function PatternsView({tab,query,onAction}:{tab:Tab;query:string;onAction:()=>void}) { const rows=matching(tab,query); return <><div className="ga-library-head"><div className="ga-library-tabs"><button className="active">All patterns <b>38</b></button><button>Active <b>31</b></button><button>In tuning <b>4</b></button><button>Drafts <b>3</b></button></div><button onClick={onAction}><Plus size={15}/>New pattern</button></div><section className="ga-pattern-grid">{rows.map((row,index)=><article className={`ga-pattern-card accent-${row.tone}`} key={row.id}><header><div className="ga-pattern-icon"><Workflow size={19}/></div><Status text={row.status} t={row.tone}/></header><span>{row.cells[0]} · {row.id}</span><h3>{row.name}</h3><p>{['Detects requests to reverse a transfer by sharing a code or sending a second payment.','Identifies people pretending to represent a trusted bank, courier or public service.','Finds promises of guaranteed returns paired with urgent requests for deposits.','Flags newly registered delivery domains requesting a clearance or release fee.'][index]}</p><div className="ga-pattern-signals"><span>Urgency</span><span>Payment request</span><span>Impersonation</span></div><footer><div><strong>{row.cells[2]}</strong><small>Matches</small></div><div><strong>{row.cells[1]}</strong><small>Severity</small></div><button>Open pattern <ChevronRight size={14}/></button></footer></article>)}</section></> }

function ChecksView({tab,query,onAction}:{tab:Tab;query:string;onAction:()=>void}) { const [kind,setKind]=useState('Message'); return <><section className="ga-check-console"><div><span className="ga-panel-kicker">Detection console</span><h2>Run a fraud check</h2><p>Analyse suspicious content without leaving the intelligence workspace.</p><div className="ga-check-kinds">{['Message','Phone','Link','Image'].map(item=><button key={item} className={kind===item?'active':''} onClick={()=>setKind(item)}>{item}</button>)}</div><div className="ga-check-input"><input placeholder={kind==='Message'?'Paste a suspicious message here…':`Enter a suspicious ${kind.toLowerCase()}…`}/><button onClick={onAction}><Zap size={15}/>Analyse</button></div></div><aside><div className="ga-mini-donut"><strong>18.4k</strong><span>Today</span></div><ul><li><i className="high"/>High risk <b>12%</b></li><li><i className="caution"/>Caution <b>22%</b></li><li><i className="safe"/>Low risk <b>66%</b></li></ul></aside></section><div className="ga-workspace-grid"><DataTable title="Live analysis stream" columns={tab.columns} rows={tab.rows} query={query}/><Breakdown title={tab.sideTitle} items={tab.side} onAction={onAction}/></div></> }

function RulesView({tab,onAction}:{tab:Tab;onAction:()=>void}) { const [enabled,setEnabled]=useState([true,true,true,false]); return <><section className="ga-rule-summary"><div><span>Rule engine health</span><strong>91.8%</strong><small>Precision across 42 active rules</small></div><div className="ga-rule-flow"><span>Input</span><i/><span>Signals</span><i/><span>Score</span><i/><span>Decision</span></div><button onClick={onAction}><Plus size={15}/>Build a rule</button></section><section className="ga-rules-layout"><div className="ga-rule-list"><header><div><span className="ga-panel-kicker">Rule stack</span><h2>Detection logic</h2></div><button>Reorder rules</button></header>{tab.rows.map((row,index)=><article key={row.id}><button className={`ga-toggle ${enabled[index]?'active':''}`} onClick={()=>setEnabled(values=>values.map((value,i)=>i===index?!value:value))}><i/></button><div className="ga-rule-copy"><span>{row.id} · {row.cells[0]}</span><strong>{row.name}</strong><small>When signal matches, add <b>{row.cells[1]}</b> to the risk score</small></div><div className="ga-rule-count"><strong>{row.cells[2]}</strong><span>Triggers</span></div><Status text={enabled[index]?'Active':'Paused'} t={enabled[index]?'green':'gold'}/><button><MoreHorizontal size={17}/></button></article>)}</div><Breakdown title={tab.sideTitle} items={tab.side} onAction={onAction}/></section></> }

function UsersView({tab,query,onAction}:{tab:Tab;query:string;onAction:()=>void}) { const rows=matching(tab,query); return <><StatGrid stats={tab.stats}/><div className="ga-user-toolbar"><div className="ga-library-tabs"><button className="active">All members</button><button>Admins</button><button>Analysts</button><button>Restricted</button></div><button onClick={onAction}><UserPlus size={15}/>Invite member</button></div><section className="ga-user-grid">{rows.map((row,index)=><article key={row.id}><header><span className="ga-avatar">{row.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><Status text={row.status} t={row.tone}/></header><h3>{row.name}</h3><p>{row.id}</p><span className="ga-role-badge">{row.cells[0]}</span><dl><div><dt>Checks</dt><dd>{row.cells[1]}</dd></div><div><dt>Reports</dt><dd>{row.cells[2]}</dd></div></dl><footer><span><i className={index<3?'online':''}/>{row.cells[3]}</span><button>Manage <ChevronRight size={13}/></button></footer></article>)}</section></> }

function AnalyticsView({tab}:{tab:Tab}) { return <><StatGrid stats={tab.stats}/><div className="ga-analytics-grid"><section className="ga-panel ga-analytics-main"><div className="ga-panel-head"><div><span className="ga-panel-kicker">Checks over time</span><h2>Detection volume</h2></div><div className="ga-chart-total"><strong>184,206</strong><span>+18.4%</span></div></div><div className="ga-area-chart"><svg viewBox="0 0 800 260" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#9828e5" stopOpacity=".28"/><stop offset="1" stopColor="#9828e5" stopOpacity="0"/></linearGradient></defs><path className="fill" d="M0 220C80 190 90 205 150 160S240 190 300 120 400 170 470 90 560 135 620 55 710 100 800 35V260H0Z"/><path className="line" d="M0 220C80 190 90 205 150 160S240 190 300 120 400 170 470 90 560 135 620 55 710 100 800 35"/></svg><div><span>1 Sep</span><span>8 Sep</span><span>15 Sep</span><span>22 Sep</span><span>29 Sep</span></div></div></section><section className="ga-panel ga-outcomes"><div className="ga-panel-head"><div><span className="ga-panel-kicker">Risk outcomes</span><h2>Result distribution</h2></div></div><div className="ga-outcome-donut"><div><strong>184k</strong><span>Total checks</span></div></div><ul><li><i className="safe"/>Low risk <b>65.9%</b></li><li><i className="caution"/>Caution <b>22.2%</b></li><li><i className="high"/>High risk <b>11.9%</b></li></ul></section></div><DataTable title={tab.title} columns={tab.columns} rows={tab.rows} query=""/></> }

function EducationView({tab,query,onAction}:{tab:Tab;query:string;onAction:()=>void}) { const rows=matching(tab,query); return <><section className="ga-featured-content"><div><span>Featured safety guide</span><h2>Mobile money scams are changing.<br/>Help people recognise the new signs.</h2><p>A practical guide built from 1,842 recent Guard checks.</p><button onClick={onAction}>Edit featured guide <ChevronRight size={14}/></button></div><BookOpen size={110}/></section><div className="ga-content-toolbar"><div className="ga-library-tabs"><button className="active">All content</button><button>Published</button><button>In review</button><button>Drafts</button></div><button onClick={onAction}><Plus size={15}/>Create article</button></div><section className="ga-content-grid">{rows.map((row,index)=><article key={row.id}><div className={`ga-content-cover cover-${index}`}><span>{row.cells[0]}</span><BookOpen size={30}/></div><div className="ga-content-copy"><Status text={row.status} t={row.tone}/><h3>{row.name}</h3><p>{row.id}</p><footer><span>{row.cells[1]} views</span><span>Updated {row.cells[2]}</span><button><MoreHorizontal size={16}/></button></footer></div></article>)}</section></> }

function AuditView({tab,query}:{tab:Tab;query:string}) { const rows=matching(tab,query); return <><div className="ga-audit-banner"><div><ShieldCheck size={24}/><div><strong>Audit integrity verified</strong><span>All events are signed and retained for 365 days.</span></div></div><span><i/>No anomalies detected</span></div><section className="ga-audit-layout"><div className="ga-panel ga-audit-timeline"><div className="ga-panel-head"><div><span className="ga-panel-kicker">Today · 29 September</span><h2>Workspace activity</h2></div><button>Download CSV</button></div>{rows.map((row,index)=><article key={row.id}><div className={`ga-audit-icon tone-${row.tone}`}>{index===3?<ShieldCheck size={16}/>:<ClipboardList size={16}/>}</div><div><strong>{row.cells[0]}</strong><p><b>{row.name}</b> · {row.cells[1]}</p><span>{row.id} · IP {row.cells[2]}</span></div><time>{row.cells[3]}</time><Status text={row.status} t={row.tone}/></article>)}</div><aside><Breakdown title={tab.sideTitle} items={tab.side} onAction={()=>{}}/><div className="ga-panel ga-audit-policy"><span className="ga-panel-kicker">Retention policy</span><strong>365 days</strong><p>Next archive: 1 October 2026</p><div><i style={{width:'76%'}}/></div></div></aside></section></> }

function WorkspaceTab({active,tab,query,onAction}:{active:Exclude<NavLabel,'Overview'|'Settings'>;tab:Tab;query:string;onAction:()=>void}) { switch(active){case 'Fraud reports':return <ReportsView tab={tab} query={query} onAction={onAction}/>;case 'Phone numbers':return <PhoneView tab={tab} query={query} onAction={onAction}/>;case 'Fraud intelligence':return <IntelligenceView tab={tab} onAction={onAction}/>;case 'Fraud patterns':return <PatternsView tab={tab} query={query} onAction={onAction}/>;case 'Fraud checks':return <ChecksView tab={tab} query={query} onAction={onAction}/>;case 'Detection rules':return <RulesView tab={tab} onAction={onAction}/>;case 'Users':return <UsersView tab={tab} query={query} onAction={onAction}/>;case 'Analytics':return <AnalyticsView tab={tab}/>;case 'Education content':return <EducationView tab={tab} query={query} onAction={onAction}/>;case 'Audit logs':return <AuditView tab={tab} query={query}/>;} }

function Overview({query,navigate}:{query:string;navigate:(n:NavLabel)=>void}) { const filtered=incidents.filter(row=>[row.name,row.id,...row.cells,row.status].join(' ').toLowerCase().includes(query.toLowerCase())); const [compare,setCompare]=useState(false); return <><StatGrid stats={overviewStats}/><section className="ga-primary-grid"><article className="ga-panel ga-health-card"><div className="ga-panel-head"><div><span className="ga-panel-kicker">Current posture</span><h2>Risk health score</h2></div><button onClick={()=>navigate('Analytics')}>View details <ChevronRight size={14}/></button></div><div className="ga-health-content"><div className="ga-gauge"><svg viewBox="0 0 150 150"><circle cx="75" cy="75" r="58"/><circle className="progress" cx="75" cy="75" r="58"/></svg><div><strong>72</strong><span>out of 100</span></div></div><div className="ga-contributors"><div className="ga-contributor-title"><strong>Top contributors</strong><span>Risk weight</span></div>{contributors.map(([label,value])=><div className="ga-contributor" key={label}><div><span>{label}</span><b>{value}%</b></div><div className="ga-mini-bar"><i style={{width:`${value}%`}}/></div></div>)}</div></div></article><article className="ga-panel ga-trend-card"><div className="ga-panel-head"><div><span className="ga-panel-kicker">Signal volume</span><h2>Risk trend</h2></div><button className={compare?'active':''} onClick={()=>setCompare(!compare)}>{compare?'Comparison on':'Compare period'}</button></div><div className="ga-bar-chart">{[45,62,39,74,58,86,69,92,76,88,64,95].map((v,i)=><i key={i} style={{height:`${v}%`}} className={i>8?'hot':''}/>)}</div><div className="ga-legend"><span><i className="orange"/>Flagged <b>1,258</b></span><span><i className="plum"/>Blocked <b>386</b></span><span><i className="violet"/>Manual review <b>142</b></span></div></article></section><DataTable title="Top alerts & incidents" columns={['Segment','Started','Owner']} rows={filtered} query=""/></> }

function Toggle({label,detail,active,onClick}:{label:string;detail:string;active:boolean;onClick:()=>void}) { return <div className="ga-setting-line"><div><strong>{label}</strong><span>{detail}</span></div><button className={`ga-toggle ${active?'active':''}`} onClick={onClick} role="switch" aria-checked={active}><i/></button></div> }
function Integration({icon,name,state}:{icon:ReactNode;name:string;state:string}) { return <div className="ga-integration"><span>{icon}</span><div><strong>{name}</strong><small>{state==='Connected'?'Sharing live workspace data':'Not yet connected'}</small></div><button className={state==='Connected'?'connected':''}>{state}</button></div> }
function SettingsView() { const [saved,setSaved]=useState(false); const [values,setValues]=useState({alerts:true,digest:true,mfa:true,exports:false}); const flip=(key:keyof typeof values)=>setValues(v=>({...v,[key]:!v[key]})); return <div className="ga-settings-grid"><section className="ga-panel ga-settings-card"><div className="ga-panel-head"><div><span className="ga-panel-kicker">Workspace profile</span><h2>Organisation details</h2></div><Database size={18}/></div><div className="ga-settings-form"><label>Workspace name<input defaultValue="Guard Ghana"/></label><label>Primary market<select defaultValue="Ghana"><option>Ghana</option><option>Nigeria</option><option>Kenya</option></select></label><label>Support email<input defaultValue="support@guard.africa"/></label><label>Timezone<select defaultValue="GMT"><option>GMT</option><option>WAT</option><option>EAT</option></select></label></div></section><section className="ga-panel ga-settings-card"><div className="ga-panel-head"><div><span className="ga-panel-kicker">Notifications</span><h2>Alerts and summaries</h2></div><Bell size={18}/></div><div className="ga-toggle-list"><Toggle label="Critical risk alerts" detail="Notify administrators about critical threats." active={values.alerts} onClick={()=>flip('alerts')}/><Toggle label="Daily intelligence digest" detail="Send a summary at 08:00 GMT." active={values.digest} onClick={()=>flip('digest')}/><Toggle label="Export completion emails" detail="Notify requesters when exports are ready." active={values.exports} onClick={()=>flip('exports')}/></div></section><section className="ga-panel ga-settings-card"><div className="ga-panel-head"><div><span className="ga-panel-kicker">Security</span><h2>Access controls</h2></div><ShieldCheck size={18}/></div><div className="ga-toggle-list"><Toggle label="Require multi-factor authentication" detail="Enforce MFA for all admin accounts." active={values.mfa} onClick={()=>flip('mfa')}/><div className="ga-setting-line"><div><strong>Session timeout</strong><span>Sign out inactive administrators.</span></div><select defaultValue="30 minutes"><option>15 minutes</option><option>30 minutes</option><option>1 hour</option></select></div></div></section><section className="ga-panel ga-settings-card"><div className="ga-panel-head"><div><span className="ga-panel-kicker">Connections</span><h2>Data integrations</h2></div><Link2 size={18}/></div><div className="ga-integration-list"><Integration icon={<MessageSquareText size={17}/>} name="WhatsApp Business" state="Connected"/><Integration icon={<Mail size={17}/>} name="Email reporting inbox" state="Connected"/><Integration icon={<Globe2 size={17}/>} name="Threat feed API" state="Configure"/></div></section><div className="ga-settings-actions"><span>{saved&&<><Check size={15}/>Settings saved</>}</span><button onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),1800)}}><Save size={16}/>Save changes</button></div></div> }

export default function AdminPage(){
  const [active,setActive]=useState<NavLabel>('Overview'); const [collapsed,setCollapsed]=useState(false); const [mobile,setMobile]=useState(false); const [query,setQuery]=useState(''); const [period,setPeriod]=useState('Last 24 hours'); const [filters,setFilters]=useState(false); const [modal,setModal]=useState(false);
  const current=active==='Overview'?{eyebrow:'Live intelligence',description:'Monitor fraud signals, emerging patterns and review activity across Guard.',action:'Create alert'}:active==='Settings'?{eyebrow:'Workspace administration',description:'Configure organisation preferences, security and connected services.',action:'Save changes'}:tabs[active];
  const select=(label:NavLabel)=>{setActive(label);setMobile(false);setQuery('')};
  return <div className={`guard-admin ${collapsed?'is-collapsed':''}`}>{mobile&&<button className="ga-mobile-scrim" onClick={()=>setMobile(false)} aria-label="Close navigation"/>}<aside className={`ga-sidebar ${mobile?'is-open':''}`}><div className="ga-brand-row"><a href="/" className="ga-brand"><span className="ga-brand-symbol"><img src="/images/guard-yellow.png" alt=""/></span><span className="ga-brand-name">Guard</span></a><button className="ga-sidebar-toggle" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<ChevronRight size={16}/>:<ChevronLeft size={16}/>}</button><button className="ga-mobile-close" onClick={()=>setMobile(false)}><X size={18}/></button></div><details className="ga-workspace"><summary className="ga-workspace-summary"><span className="ga-avatar ga-avatar-small">GH</span><div className="ga-workspace-copy"><strong>Guard Ghana</strong><span>Admin workspace</span></div><ChevronDown size={14}/></summary><div className="ga-workspace-menu"><span className="ga-workspace-menu-label">Choose dashboard</span><Link href="/admin" className="active"><span className="ga-workspace-menu-icon"><LayoutDashboard size={16}/></span><span><strong>Admin dashboard</strong><small>Manage Guard operations</small></span><Check size={15}/></Link><Link href="/dashboard" onClick={()=>setMobile(false)}><span className="ga-workspace-menu-icon"><Users size={16}/></span><span><strong>User dashboard</strong><small>View the customer experience</small></span><ChevronRight size={15}/></Link></div></details><div className="ga-nav-label">Workspace</div><nav className="ga-nav">{navigation.map(([label,Icon])=><button key={label} className={active===label?'active':''} onClick={()=>select(label)} title={collapsed?label:undefined}><Icon size={18}/><span>{label}</span>{label==='Fraud reports'&&<em>12</em>}</button>)}</nav><div className="ga-sidebar-foot"><div className="ga-system-status"><span/><div><strong>Systems operational</strong><small>Updated 2 min ago</small></div></div><div className="ga-profile"><span className="ga-avatar">AO</span><div><strong>Adwoa Owusu</strong><span>Administrator</span></div><button onClick={()=>select('Settings')}><Settings size={15}/></button></div></div></aside>
    <main className="ga-main"><header className="ga-topbar"><button className="ga-mobile-menu" onClick={()=>setMobile(true)}><Menu size={20}/></button><div className="ga-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${active.toLowerCase()}`}/><kbd>⌘ K</kbd></div><div className="ga-top-actions"><button className="ga-icon-button"><RefreshCcw size={18}/></button><button className="ga-icon-button ga-notification"><Bell size={18}/><span/></button><button className="ga-create" onClick={()=>setModal(true)}><Plus size={17}/>{current.action}</button></div></header><div className="ga-content"><section className="ga-page-head"><div><div className="ga-eyebrow"><Activity size={14}/>{current.eyebrow}</div><h1>{active==='Overview'?'Risk overview':active}</h1><p>{current.description}</p></div>{active!=='Settings'&&<div className="ga-page-controls"><label><span>Period</span><select value={period} onChange={e=>setPeriod(e.target.value)}><option>Last 24 hours</option><option>Last 7 days</option><option>Last 30 days</option></select></label><button className={filters?'is-active':''} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={16}/>Filters {filters&&<span>2</span>}</button></div>}</section>{filters&&active!=='Settings'&&<div className="ga-filter-bar"><span>Active filters</span><button>Ghana <X size={12}/></button><button>All channels <X size={12}/></button><button className="ga-clear" onClick={()=>setFilters(false)}>Clear all</button></div>}{active==='Overview'?<Overview query={query} navigate={select}/>:active==='Settings'?<SettingsView/>:<WorkspaceTab active={active} tab={tabs[active]} query={query} onAction={()=>setModal(true)}/>}<footer className="ga-data-note"><span><i/>Live data</span><p>Signals refresh automatically every 60 seconds.</p><strong>Guard intelligence engine</strong></footer></div></main>
    {modal&&<div className="ga-modal-layer"><button className="ga-modal-scrim" onClick={()=>setModal(false)}/><div className="ga-modal"><div className="ga-modal-icon">{active==='Users'?<UserPlus size={21}/>:active==='Fraud checks'?<Zap size={21}/>:<Bell size={21}/>}</div><button className="ga-modal-close" onClick={()=>setModal(false)}><X size={18}/></button><span className="ga-panel-kicker">{current.eyebrow}</span><h2>{current.action}</h2><p>Set up the details below. This prototype keeps your dashboard state local.</p><label>Name<input placeholder={`Name this ${current.action.toLowerCase()}`}/></label><label>Priority<select defaultValue="High"><option>High</option><option>Medium</option><option>Low</option></select></label><div className="ga-modal-actions"><button onClick={()=>setModal(false)}>Cancel</button><button className="primary" onClick={()=>setModal(false)}>{current.action}</button></div></div></div>}
  </div>;
}
