import Link from 'next/link';
import { ArrowRight, CheckCircle2, Database, Eye, LockKeyhole, MessageSquareWarning, ShieldCheck, UsersRound } from 'lucide-react';
import { Footer, Header } from '@/components/Header';

const steps = [
  { icon: MessageSquareWarning, number:'01', title:'You choose to report', text:'Share a suspicious message, number, link, payment route, or description through the dedicated report form.' },
  { icon: LockKeyhole, number:'02', title:'Guard removes direct identifiers', text:'The system strips common email addresses and Ghana phone numbers from the dataset candidate before review.' },
  { icon: Eye, number:'03', title:'A human verifies it', text:'An authorised analyst labels it Fraud, Legitimate, or Uncertain and assigns the right category.' },
  { icon: Database, number:'04', title:'Only verified data advances', text:'Approved records can enter a versioned dataset. Pending reports never trigger automatic retraining.' },
];

export default function ContributePage(){
  return <><Header/><main className="contribute-page"><section className="contribute-hero"><div className="container contribute-hero-grid"><div><span className="eyebrow">Public fraud intelligence for Ghana</span><h1>Share one warning. Help protect the next person.</h1><p>Contribute suspicious payment messages, links, numbers, accounts, or fraud stories to Guard&apos;s moderated intelligence system. Your private checks are never added automatically.</p><div className="contribute-actions"><Link href="/report" className="btn btn-primary">Contribute a report <ArrowRight size={16}/></Link><Link href="/detect" className="btn btn-outline">Make a private check</Link></div><small><ShieldCheck size={15}/> Consent required · de-identified · human reviewed</small></div><aside><div className="contribute-card-mark"><img src="/images/guard-yellow.png" alt=""/></div><strong>Safe contribution checklist</strong><ul><li><CheckCircle2 size={16}/> Remove PINs, passwords and OTPs</li><li><CheckCircle2 size={16}/> Share only what you are allowed to share</li><li><CheckCircle2 size={16}/> Describe what happened clearly</li><li><CheckCircle2 size={16}/> Keep useful numbers, links and payment context</li></ul></aside></div></section><section className="container contribute-flow"><div className="contribute-heading"><span className="eyebrow">How public reports become trusted data</span><h2>Collection with a review gate.</h2><p>Guard separates a private fraud check from an intentional contribution. That boundary keeps unreviewed or accidental submissions out of model training.</p></div><div className="contribute-steps">{steps.map(({icon:Icon,...step})=><article key={step.number}><span>{step.number}</span><Icon size={23}/><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></section><section className="container contribute-types"><div><UsersRound size={24}/><h2>What the public can contribute</h2><p>Suspicious Mobile Money requests, fake payment alerts, WhatsApp impersonation, phishing links, fraudulent shops, bank impersonation, investment scams, and new local patterns.</p></div><div><LockKeyhole size={24}/><h2>What Guard will not collect silently</h2><p>The content of an ordinary private check. A contribution requires a separate report action and explicit consent. Usefulness feedback contains no checked message, number, or link.</p></div></section><section className="contribute-final"><div className="container"><div><span className="eyebrow">Help build the signal</span><h2>Seen something suspicious?</h2><p>Your report can help Guard recognise recurring patterns after an analyst verifies it.</p></div><Link href="/report" className="btn btn-primary">Report it safely <ArrowRight size={16}/></Link></div></section></main><Footer/></>;
}
