'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, CheckCircle2, FileUp, ShieldAlert } from 'lucide-react';
import { Header, Footer } from './Header';

type Kind = 'message'|'screenshot'|'link'|'number'|'payment'|'call';
const meta: Record<Kind,{title:string;prompt:string;placeholder:string;button:string}> = {
 message:{title:'Check a suspicious message',prompt:'Paste the suspicious message',placeholder:'Paste the SMS, WhatsApp message, email, DM or offer here…',button:'Analyse Message'},
 screenshot:{title:'Check a suspicious screenshot',prompt:'Upload the screenshot you want Guard to inspect',placeholder:'',button:'Analyse Screenshot'},
 link:{title:'Check a suspicious link',prompt:'Paste suspicious link',placeholder:'https://example.com/verify-account',button:'Check Link'},
 number:{title:'Check a phone number',prompt:'Enter phone number',placeholder:'024 XXX XXXX or +233 24 XXX XXXX',button:'Check Number'},
 payment:{title:'Check a payment request',prompt:'Tell us about the request',placeholder:'Describe who requested payment, what they said, and how you were asked to pay…',button:'Check Payment Request'},
 call:{title:'Check a suspicious call',prompt:'Describe the call',placeholder:'What did the caller claim, and what did they request?',button:'Analyse Call'}
};
export function Checker({kind}:{kind:Kind}) { const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const [result,setResult]=useState<null|{level:string;reason:string;signals:string[];action:string}>(null); const m=meta[kind];
 const submit=async()=>{setLoading(true); try {const r=await fetch('/api/analyse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,input})}); setResult(await r.json());} finally {setLoading(false);} };
 return <><Header/><main className="page-shell"><div className="container"><Link href="/detect" className="small-link"><ArrowLeft size={14} style={{verticalAlign:'-2px'}}/> Back to all checks</Link><div className="page-title" style={{marginTop:25}}><div className="eyebrow">{kind === 'number' ? 'Reputation lookup' : 'Fraud check'}</div><h1>{result ? 'Guard’s read on this interaction' : m.title}</h1><p>{result ? 'Use these signals as decision support. Guard never provides an absolute guarantee.' : 'Submit only what you are comfortable sharing. Treat everything you upload as private, untrusted content.'}</p></div>{result ? <Result result={result} kind={kind}/> : <div className="form-panel"><label className="label">{m.prompt}</label>{kind==='screenshot' ? <div style={{border:'1px dashed #9cc8c3',padding:'38px 20px',textAlign:'center',borderRadius:8,background:'#f8fcfb'}}><FileUp size={28} color="#0f9d8c"/><p style={{margin:'12px 0 4px',fontWeight:700,color:'var(--navy)'}}>Drop an image here or choose a file</p><p className="helper">PNG, JPG, JPEG or WEBP · Max 10 MB</p><input type="file" accept="image/png,image/jpeg,image/webp" style={{marginTop:16,maxWidth:'100%'}} onChange={e=>setInput(e.target.files?.[0]?.name || '')}/></div> : kind==='call' || kind==='payment' ? <><select className="select"><option>{kind==='call'?'Bank':'Individual or business'}</option><option>Telecom provider</option><option>Mobile-money provider</option><option>Government organisation</option><option>Other</option></select><textarea className="textarea" placeholder={m.placeholder} value={input} onChange={e=>setInput(e.target.value)} /></> : <textarea className={kind==='link'||kind==='number'?'input':'textarea'} placeholder={m.placeholder} value={input} onChange={e=>setInput(e.target.value)} />}{kind==='message'&&<p className="helper">Guard looks for requests for OTPs, PINs, urgency, impersonation, suspicious links and other warning signs.</p>}<button className="btn btn-primary" style={{marginTop:22}} onClick={submit} disabled={loading}>{loading?'Analysing…':m.button}<ArrowRight size={16}/></button></div>}</div></main><Footer/></> }
function Result({result,kind}:{result:{level:string;reason:string;signals:string[];action:string};kind:Kind}){return <div className="result-card"><div className="result-top"><span className="risk-dot"/><div><div className="eyebrow" style={{marginBottom:8}}>Assessment · {kind}</div><h2>{result.level}</h2><p>{result.reason}</p></div></div><div className="result-body"><div><h3>Warning signs detected</h3><ul className="signal-list">{result.signals.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>Recommended action</h3><div className="notice"><ShieldAlert size={16} style={{verticalAlign:'-3px',marginRight:6}}/>{result.action}</div><div style={{display:'flex',gap:10,marginTop:24,flexWrap:'wrap'}}><Link href="/report" className="btn btn-outline">Report This</Link><Link href="/detect" className="btn btn-primary">Check Something Else</Link></div></div></div></div>}
