'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Check, FileUp, MessageCircle, Network, Radar, ShieldAlert, TriangleAlert } from 'lucide-react';
import { Header, Footer } from './Header';

export type Kind = 'message'|'screenshot'|'link'|'number'|'whatsapp'|'payment'|'call';
export type AnalysisResult = {level:string;reason:string;signals:string[];action:string;score?:number;pattern?:string};
const meta: Record<Kind,{title:string;prompt:string;placeholder:string;button:string}> = {
 message:{title:'Check a suspicious message',prompt:'Paste the suspicious message',placeholder:'Paste the SMS, WhatsApp message, email, DM or offer here…',button:'Analyse Message'},
 screenshot:{title:'Check a suspicious screenshot',prompt:'Upload the screenshot you want Guard to inspect',placeholder:'',button:'Analyse Screenshot'},
 link:{title:'Check a suspicious link',prompt:'Paste suspicious link',placeholder:'https://example.com/verify-account',button:'Check Link'},
 number:{title:'Check a phone number',prompt:'Enter phone number',placeholder:'024 XXX XXXX or +233 24 XXX XXXX',button:'Check Number'},
 whatsapp:{title:'Check a WhatsApp number',prompt:'Enter the WhatsApp number',placeholder:'024 XXX XXXX or +233 24 XXX XXXX',button:'Check WhatsApp Number'},
 payment:{title:'Check before you send money',prompt:'Tell Guard about the Mobile Money or payment request',placeholder:'Include the amount, recipient name or number, what they claimed, and how they asked you to pay…',button:'Check Before Paying'},
 call:{title:'Check a suspicious call',prompt:'Describe the call',placeholder:'What did the caller claim, and what did they request?',button:'Analyse Call'}
};
export function Checker({kind,initialInput='',autoStart=false}:{kind:Kind;initialInput?:string;autoStart?:boolean}) { const [input,setInput]=useState(initialInput); const [loading,setLoading]=useState(false); const [autoStarted,setAutoStarted]=useState(false); const [result,setResult]=useState<AnalysisResult|null>(null); const m=meta[kind];
 const submit=async()=>{setResult(null);setLoading(true);window.scrollTo({top:0,behavior:'smooth'});const startedAt=Date.now(); try {const r=await fetch('/api/analyse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,input})}); const nextResult=await r.json(); const remaining=Math.max(0,2200-(Date.now()-startedAt)); if(remaining>0) await new Promise(resolve=>window.setTimeout(resolve,remaining)); setResult(nextResult);} finally {setLoading(false);} };
 useEffect(() => { if(autoStart && initialInput && !autoStarted) { setAutoStarted(true); submit(); } }, [autoStart,initialInput,autoStarted]);
 return <><Header/><main className={'page-shell '+(loading||result?'checker-loading-shell':'')}><div className={'container '+(loading||result?'checker-stage':'')}>{result ? <GuardResult result={result} kind={kind}/> : loading ? <AnalysisScanner kind={kind}/> : <><div className="page-title"><div className="eyebrow">{kind === 'number' || kind === 'whatsapp' ? 'Reputation lookup' : 'Fraud check'}</div><h1>{m.title}</h1><p>{kind === 'whatsapp' ? 'Check for community reports and takeover warning signs. A clean result is not proof that the account is safe.' : 'Submit only what you are comfortable sharing. Treat everything you upload as private, untrusted content.'}</p></div><div className="form-panel"><label className="label">{m.prompt}</label>{kind==='screenshot' ? <div style={{border:'1px dashed #9cc8c3',padding:'38px 20px',textAlign:'center',borderRadius:8,background:'#f8fcfb'}}><FileUp size={28} color="#0f9d8c"/><p style={{margin:'12px 0 4px',fontWeight:700,color:'var(--navy)'}}>Drop an image here or choose a file</p><p className="helper">PNG, JPG, JPEG or WEBP · Max 10 MB</p><input type="file" accept="image/png,image/jpeg,image/webp" style={{marginTop:16,maxWidth:'100%'}} onChange={e=>setInput(e.target.files?.[0]?.name || '')}/></div> : kind==='call' || kind==='payment' ? <><select className="select"><option>{kind==='call'?'Bank':'Individual or business'}</option><option>Telecom provider</option><option>Mobile-money provider</option><option>Government organisation</option><option>Other</option></select><textarea className="textarea" placeholder={m.placeholder} value={input} onChange={e=>setInput(e.target.value)} /></> : <textarea className={kind==='link'||kind==='number'||kind==='whatsapp'?'input':'textarea'} placeholder={m.placeholder} value={input} onChange={e=>setInput(e.target.value)} />}{kind==='message'&&<p className="helper">Guard looks for requests for OTPs, PINs, urgency, impersonation, suspicious links and other warning signs.</p>}{kind==='whatsapp'&&<p className="helper">If the account belongs to someone you know, verify through a different trusted channel before sending money or sharing a code.</p>}<button className="btn btn-primary" style={{marginTop:22}} onClick={submit}>{m.button}<ArrowRight size={16}/></button></div></>}</div></main><Footer/></> }

export function AnalysisScanner({kind,compact=false,active=true,hero=false}:{kind:Kind;compact?:boolean;active?:boolean;hero?:boolean}) {
 const stages = ['Reading the payment and evidence','Detecting suspicious requests and pressure','Comparing recipient and Guard risk signals','Preparing a safer next action'];
 const [stage, setStage] = useState(0);
 useEffect(() => { if(!active) return; const timer = window.setInterval(() => setStage(current => Math.min(current + 1, stages.length - 1)), 900); return () => window.clearInterval(timer); }, [active,stages.length]);
 const statusText = active ? stages[stage] : 'Ready for your submission';
 return <section className={'analysis-scanner'+(compact?' analysis-scanner-compact':'')+(hero?' analysis-scanner-hero':'')+(!active?' analysis-scanner-ready':'')} role="status" aria-live="polite" aria-label={active?'Guard is analysing your submission':'Guard scanner is ready'}>
   <div className="analysis-copy"><div className="eyebrow analysis-eyebrow"><Radar size={14}/> {active ? 'Guard is protecting the decision' : 'Guard fraud scanner'}</div><h2>{active ? `Checking this ${kind === 'number' ? 'number' : kind} before money moves.` : 'Check before you pay.'}</h2><p>{active ? 'Guard is reviewing the payment context and available evidence, then it will explain whether you should pause, verify, or avoid the transaction.' : 'Choose the payment request or evidence you received. Guard will explain the warning signs before you act.'}</p><div className="analysis-progress"><span style={{width:`${active ? ((stage + 1) / stages.length) * 100 : 100}%`}}/></div><div className="analysis-stage"><span className="analysis-stage-dot"/>{statusText}<small>{active ? `${stage + 1}/${stages.length}` : 'READY'}</small></div></div>
   <div className="analysis-business-orbit" aria-hidden="true"><div className="analysis-business-ring analysis-business-ring-outer"/><div className="analysis-business-ring analysis-business-ring-inner"/><div className="analysis-business-core"><img src="/images/guard-yellow.png" alt=""/><span>Analysing signals</span></div></div>
 </section>;
}
export function GuardResult({result,kind}:{result:AnalysisResult;kind:Kind}){const score=result.score ?? (result.level==='High Risk'?82:result.level==='Caution'?54:result.level==='Low Risk'?12:24);const riskColor=result.level==='High Risk'?'#ef554f':result.level==='Low Risk'?'#35c98f':result.level==='Caution'?'#ffb52e':'#b881e7';const rows=[{label:'Risk pattern',value:result.pattern||`${kind} risk review`,Icon:TriangleAlert},{label:'Detected signal',value:result.signals[0]||'No deterministic warning signal was found',Icon:Network},{label:'Payment context',value:result.signals[1]||(kind==='whatsapp'||kind==='number'?'Verify the owner and payment recipient independently':'No additional matching context is currently available'),Icon:MessageCircle}];return <section className="guard-result-wrap"><div className={'guard-result-card guard-result-'+result.level.toLowerCase().replaceAll(' ','-')}><div className="guard-result-top"><span><img src="/images/guard-yellow.png" alt=""/>Guard payment protection review</span><b>{result.level}</b></div><div className="guard-result-assessment"><div className="guard-result-score" style={{background:`conic-gradient(${riskColor} 0 ${score*3.6}deg,#3b244d ${score*3.6}deg 360deg)`}}><div><strong>{score}</strong><small>Risk score</small></div></div><div className="guard-result-summary"><span>Before you pay · {kind}</span><h1>{result.level}</h1><p>{result.reason}</p></div><div className="guard-result-facts"><div><span>Evidence</span><strong>{kind}</strong></div><div><span>Signals reviewed</span><strong>{result.signals.length}</strong></div><div><span>Payment status</span><strong>Decision pending</strong></div></div></div><div className="guard-result-signals">{rows.map(({label,value,Icon})=><div key={label}><span><Icon size={17}/>{label}</span><strong>{value}</strong></div>)}</div><div className="guard-result-action"><Check size={19}/><strong>{result.action}</strong></div></div><div className="guard-result-followup"><div><span className="eyebrow">Protect your money</span><h2>Do not pay on a score alone.</h2><p>Use this assessment as a reason to pause. Confirm the recipient name, amount, request, and transaction through a separate trusted channel before sending money or releasing goods.</p></div><div className="guard-result-next"><span className="eyebrow">Help prevent the next loss</span><p>Report the suspicious payment route, number, account, message, or link so Guard can connect recurring fraud signals.</p><div className="guard-result-buttons"><Link href="/report" className="btn btn-outline"><ShieldAlert size={15}/> Report this payment</Link><Link href="/detect" className="btn btn-primary">Check another payment <ArrowRight size={15}/></Link></div></div></div></section>}
