import Link from 'next/link';
import { ArrowRight, BadgeCheck, BellRing, FileImage, Link2, MessageSquare, Phone, Shield, WalletCards } from 'lucide-react';
import { Header, Footer } from './Header';
import { QuickCheck } from './QuickCheck';

const checks = [
  ['Suspicious Messages','Check SMS, WhatsApp, social-media messages and other suspicious text.',MessageSquare,'/detect/message'],
  ['Screenshots','Upload suspicious conversations, offers or payment requests.',FileImage,'/detect/screenshot'],
  ['Links & Websites','Analyse a URL before opening it or trusting what it asks.',Link2,'/detect/link'],
  ['Phone Numbers','Check reputation signals and moderated community reports.',Phone,'/detect/number'],
  ['Payment Requests','Assess sellers, recipients, payment instructions and inconsistencies.',WalletCards,'/detect/payment'],
  ['Suspicious Calls','Tell Guard what a caller claimed and requested.',BellRing,'/detect/call']
] as const;
const frauds = ['Mobile Money Fraud','Bank Impersonation','Phishing','Fake Online Shops','Investment Fraud','Job Scams','Account Takeover','Delivery Scams'];
const communitySignals = [
  ['Mobile money message', '“You have received a bonus. Pay a small fee to withdraw.”', 'Payment request', MessageSquare],
  ['Fake delivery link', '“Your parcel is waiting. Confirm your address now.”', 'Suspicious link', Link2],
  ['Impersonation call', '“Your account will be blocked unless you share the code.”', 'OTP request', Phone],
] as const;

export function Home() { return <><Header overlay/><main>
  <section className="hero"><div className="container hero-grid"><div className="hero-copy-layer"><div className="eyebrow">Guard’s free fraud checker</div><h1>Not sure if it’s safe?<br/>Check it with <span className="hero-brand-word">Guard</span>.</h1><p className="hero-copy">Safely check suspicious URLs, phone numbers, payment requests and messages before you act.</p><QuickCheck/><div className="hero-trust"><BadgeCheck size={16}/> No account needed for a quick check</div></div><div className="hero-art"><div className="proof-card"><strong><BadgeCheck size={15} style={{verticalAlign:'-3px',marginRight:6,color:'#6d22b7'}}/>Decision support, in plain language</strong><span>Pause. Check. Decide with more confidence.</span></div></div></div></section>
  <section className="partner-strip"><div className="container"><div className="partner-copy"><span className="eyebrow">Growing the safety ecosystem</span><strong>Exploring partnerships with trusted organisations</strong></div><div className="partner-marks" aria-label="Potential partner categories"><span>MTN</span><span>Banking partners</span><span>CSA Ghana</span><span>Mobile money</span><span>Community networks</span></div></div></section>
  <section className="section community-section"><div className="container"><div className="section-head community-head"><div><div className="eyebrow">Community signals</div><h2>What people are seeing.</h2></div><p>Patterns become easier to recognise when people share what reached them. These examples show the kinds of signals Guard helps you slow down and inspect.</p></div><div className="community-grid">{communitySignals.map(([title,quote,tag,Icon])=><article className="community-card" key={title}><div className="community-card-top"><span className="icon-box"><Icon size={18}/></span><span className="ds-pill ds-pill-lilac">{tag}</span></div><h3>{title}</h3><p>{quote}</p><div className="community-card-foot"><span><span className="community-dot"/> Seen in community reports</span><Link href="/detect" aria-label={'Check '+title}>Check this pattern <ArrowRight size={13}/></Link></div></article>)}</div><div className="common-scam-row"><div><div className="eyebrow">Browse common scams</div><strong>Start with the pattern that feels familiar.</strong></div><div className="common-scam-tags">{frauds.slice(0,6).map(x=><Link href="/learn" key={x}>{x}<ArrowRight size={12}/></Link>)}</div></div></div></section>
  <section className="section feature-section"><div className="container"><div className="section-head split-head"><div><div className="eyebrow">Our approach</div><h2>Essential protection for everyday digital life</h2></div><p>Fraud can arrive as a message, call, link or payment request. Guard helps you slow the moment down and understand what deserves a closer look.</p></div><div className="card-grid">{checks.map(([title,desc,Icon,href],i)=><Link href={href} className={'feature-card feature-'+i} key={title}><div className="icon-box"><Icon size={19}/></div><h3>{title}</h3><p>{desc}</p><span className="card-arrow">Explore check <ArrowRight size={14}/></span></Link>)}</div></div></section>
  <section className="section" style={{background:'#fff'}}><div className="container"><div className="section-head"><div className="eyebrow">How it works</div><h2>Clarity before action.</h2></div><div className="steps">{[['01','Submit','Share the suspicious interaction with Guard.'],['02','Analyse','Rules, reputation signals and context are combined.'],['03','Understand','See the warning signs in language that makes sense.'],['04','Decide','Choose the next step with more confidence.']].map(([n,t,d])=><div className="step" key={n}><div className="step-num">{n}</div><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
  <section className="dark-band"><div className="container" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:60,alignItems:'center'}}><div><div className="eyebrow" style={{color:'#ffb52e'}}>Built for real life</div><h2>Fraud does not always look suspicious at first.</h2><p>Guard brings together explainable signals, community intelligence and practical next steps — without asking you to become a security expert.</p><Link href="/learn" className="btn btn-lime">Explore fraud awareness <ArrowRight size={16}/></Link></div><div><div className="eyebrow" style={{color:'#ffb52e'}}>Common fraud types</div><div className="tag-list">{frauds.map(x=><span className="tag" key={x}>{x}</span>)}</div></div></div></section>
  <section className="section"><div className="container" style={{textAlign:'center'}}><div className="eyebrow">Your next decision</div><h2>Not sure if you can trust it?<br/>Guard it first.</h2><Link href="/detect" className="btn btn-primary">Check for Fraud <ArrowRight size={16}/></Link></div></section>
  </main><Footer/></> }
