import Link from 'next/link';
import { ArrowRight, BarChart3, Check, Network, ShieldCheck } from 'lucide-react';
import { Header, Footer } from '@/components/Header';

const businessPlans = [
  { name: 'Pilot', price: 'Free', copy: 'Explore Guard with a small support team.', features: ['Up to 3 team members', '100 checks per month', 'Shared review notes'], action: 'Start a pilot', href: '/register', featured: false },
  { name: 'Growth', price: 'GHS 1,500 / mo', copy: 'For teams actively managing customer risk.', features: ['Up to 15 team members', 'Unlimited checks', 'Risk dashboard and history'], action: 'Choose Growth', href: '/report', featured: true },
  { name: 'Scale', price: 'Let’s talk', copy: 'For organisations building fraud operations.', features: ['Custom team access', 'Configurable detection rules', 'Priority intelligence support'], action: 'Talk to Guard', href: '/report', featured: false },
];

export default function Business() { return <><Header/><main className="page-shell"><div className="container"><div className="page-title"><div className="eyebrow">For businesses and support teams</div><h1>Turn fraud signals into better protection.</h1><p>Guard helps organisations understand recurring suspicious patterns across phone numbers, links, payment requests and customer reports.</p><Link href="/report" className="btn btn-primary">Talk to Guard <ArrowRight size={15}/></Link></div><div className="card-grid"><div className="feature-card"><div className="icon-box"><Network size={19}/></div><h3>Shared intelligence</h3><p>Connect reports and related entities into a clearer picture of emerging fraud patterns.</p></div><div className="feature-card"><div className="icon-box"><BarChart3 size={19}/></div><h3>Operational visibility</h3><p>Track checks, risk distribution, review queues and evidence-backed reports.</p></div><div className="feature-card"><div className="icon-box"><ShieldCheck size={19}/></div><h3>Explainable signals</h3><p>Give teams consistent decision support without relying on black-box conclusions.</p></div></div><section className="business-pricing"><div className="section-head"><div className="eyebrow">Simple business pricing</div><h2>Start small. Scale when the signals grow.</h2><p>Choose a clear starting point for your team, then move up when you need more collaboration, history, and intelligence.</p></div><div className="pricing-grid">{businessPlans.map(plan=><div className={'price-card '+(plan.featured?'price-card-featured':'')} key={plan.name}>{plan.featured&&<span className="price-badge">Recommended</span>}<h3>{plan.name}</h3><div className="price-value">{plan.price}</div><p>{plan.copy}</p><ul>{plan.features.map(feature=><li key={feature}><Check size={15}/>{feature}</li>)}</ul><Link href={plan.href} className={'btn '+(plan.featured?'btn-primary':'btn-outline')}>{plan.action}<ArrowRight size={15}/></Link></div>)}</div></section></div></main><Footer/></> }
