-- Guard MVP schema. Run in Supabase SQL editor or migration runner.
create extension if not exists "uuid-ossp";

create type public.user_role as enum ('user','super_admin','fraud_analyst','support_admin');
create type public.risk_level as enum ('low','caution','high','unable_to_determine');
create type public.report_status as enum ('submitted','under_review','verified_signal','insufficient_evidence','rejected','appealed','archived');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, role public.user_role not null default 'user', privacy_preferences jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.fraud_categories (id uuid primary key default uuid_generate_v4(), name text not null unique, slug text not null unique, description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.fraud_signals (id uuid primary key default uuid_generate_v4(), key text not null unique, name text not null, weight integer not null default 10, severity text not null default 'medium', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.checks (id uuid primary key default uuid_generate_v4(), user_id uuid references public.profiles(id) on delete set null, check_type text not null, input_metadata jsonb not null default '{}'::jsonb, status text not null default 'submitted', is_saved boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.analysis_results (id uuid primary key default uuid_generate_v4(), check_id uuid not null references public.checks(id) on delete cascade, risk_level public.risk_level not null, risk_score integer check (risk_score between 0 and 100), likely_pattern text, explanation text, recommended_action text, model_metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.uploaded_assets (id uuid primary key default uuid_generate_v4(), owner_id uuid references public.profiles(id) on delete set null, check_id uuid references public.checks(id) on delete cascade, bucket text not null, object_path text not null, mime_type text not null, size_bytes bigint, retention_until timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.check_signals (check_id uuid references public.checks(id) on delete cascade, signal_id uuid references public.fraud_signals(id) on delete cascade, evidence text, weight_applied integer, primary key (check_id, signal_id));
create table public.fraud_patterns (id uuid primary key default uuid_generate_v4(), name text not null, description text, category_id uuid references public.fraud_categories(id), severity text, status text default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.phone_entities (id uuid primary key default uuid_generate_v4(), normalized_number text not null unique, country_code text default 'GH', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.domain_entities (id uuid primary key default uuid_generate_v4(), domain text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.payment_entities (id uuid primary key default uuid_generate_v4(), identifier text not null unique, provider text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.social_entities (id uuid primary key default uuid_generate_v4(), handle text not null unique, platform text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.fraud_reports (id uuid primary key default uuid_generate_v4(), reporter_id uuid references public.profiles(id) on delete set null, category_id uuid references public.fraud_categories(id), status public.report_status not null default 'submitted', description text not null, entity_type text, entity_value text, amount_requested numeric, amount_lost numeric, incident_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.fraud_report_evidence (id uuid primary key default uuid_generate_v4(), report_id uuid not null references public.fraud_reports(id) on delete cascade, bucket text not null default 'fraud-report-evidence', object_path text not null, mime_type text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.entity_relationships (id uuid primary key default uuid_generate_v4(), from_type text not null, from_id uuid not null, relationship text not null, to_type text not null, to_id uuid not null, confidence numeric default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.reputation_scores (id uuid primary key default uuid_generate_v4(), entity_type text not null, entity_id uuid not null, report_count integer default 0, independent_reporters integer default 0, evidence_count integer default 0, score integer default 0, moderated boolean default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.feedback (id uuid primary key default uuid_generate_v4(), user_id uuid references public.profiles(id) on delete set null, check_id uuid references public.checks(id) on delete cascade, helpful boolean, comment text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.appeals (id uuid primary key default uuid_generate_v4(), report_id uuid references public.fraud_reports(id) on delete cascade, user_id uuid references public.profiles(id) on delete set null, reason text not null, status text default 'submitted', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.education_content (id uuid primary key default uuid_generate_v4(), slug text unique not null, title text not null, body jsonb not null default '{}'::jsonb, published boolean default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.admin_notes (id uuid primary key default uuid_generate_v4(), admin_id uuid references public.profiles(id) on delete set null, report_id uuid references public.fraud_reports(id) on delete cascade, note text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default uuid_generate_v4(), actor_id uuid references public.profiles(id) on delete set null, action text not null, target_type text, target_id uuid, metadata jsonb default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.checks enable row level security; alter table public.analysis_results enable row level security; alter table public.uploaded_assets enable row level security; alter table public.fraud_reports enable row level security; alter table public.fraud_report_evidence enable row level security; alter table public.feedback enable row level security; alter table public.appeals enable row level security;
create policy "profiles own row" on public.profiles for select using (auth.uid() = id);
create policy "checks own rows" on public.checks for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "analysis follows own check" on public.analysis_results for select using (exists (select 1 from public.checks c where c.id=check_id and c.user_id=auth.uid()));
create policy "assets own rows" on public.uploaded_assets for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
create policy "reports own rows" on public.fraud_reports for all using (auth.uid() = reporter_id) with check (auth.uid() = reporter_id);
create policy "report evidence own rows" on public.fraud_report_evidence for select using (exists (select 1 from public.fraud_reports r where r.id=report_id and r.reporter_id=auth.uid()));
create policy "feedback own rows" on public.feedback for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "appeals own rows" on public.appeals for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into public.fraud_signals (key,name,weight,severity) values
 ('otp_request','OTP Request',35,'high'),('pin_request','PIN Request',45,'critical'),('password_request','Password Request',35,'high'),('urgency','Urgency',10,'medium'),('fear_or_threat','Fear or Threat',18,'high'),('advance_payment','Advance Payment',25,'high'),('guaranteed_return','Guaranteed Return',25,'high'),('suspicious_domain','Suspicious URL',25,'high'),('impersonation','Impersonation',25,'high'),('remote_access_request','Remote Access Request',40,'critical') on conflict (key) do nothing;
